# Generated by Django 5.1.2 on 2024-10-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('info', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(default='default.JPG', upload_to='tour_photo', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='tour',
            name='text',
            field=models.TextField(default='Тур', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='tour.town', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Hotel_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FilePathField(verbose_name='Путь до картинки')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.hotel', verbose_name='Отель')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
            ],
        ),
    ]
