# Generated by Django 5.1.2 on 2024-10-19 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_hotel_tour_photo_tour_text_alter_tour_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='date',
        ),
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата конца'),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала'),
        ),
    ]
