# Generated by Django 5.1.2 on 2024-10-22 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_tour_date_tour_end_date_tour_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название экскурсии')),
                ('interval', models.CharField(max_length=50, verbose_name='Продолжительность')),
                ('description', models.TextField(default='Экскурсия', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Экскурсии',
            },
        ),
        migrations.AlterModelOptions(
            name='hotel_photo',
            options={'verbose_name': 'Фото отеля', 'verbose_name_plural': 'Фото отелей'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='adress',
            field=models.CharField(default='Гагра', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hotel_photo',
            name='image_url',
            field=models.CharField(default='', max_length=100, verbose_name='Путь до картинки'),
        ),
        migrations.CreateModel(
            name='Tour_Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.excursion', verbose_name='Экскурсия')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Тур-Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='Tour_Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.hotel', verbose_name='Отель')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Тур-Отели',
            },
        ),
        migrations.DeleteModel(
            name='Tour_Info',
        ),
    ]
