# Generated by Django 5.1.2 on 2024-10-25 11:44

import tour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_excursion_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'verbose_name': 'Экскурсия', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AlterModelOptions(
            name='tour_excursion',
            options={'verbose_name': 'Тур_Экскурсия', 'verbose_name_plural': 'Тур-Экскурсии'},
        ),
        migrations.AlterModelOptions(
            name='tour_hotel',
            options={'verbose_name': 'Тур_Отель', 'verbose_name_plural': 'Тур-Отели'},
        ),
        migrations.RemoveField(
            model_name='excursion_photo',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='hotel_photo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='excursion_photo',
            name='photo',
            field=models.ImageField(default='default.JPG', upload_to=tour.models.Excursion_photo.get_excursion_upload_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='hotel_photo',
            name='photo',
            field=models.ImageField(default='default.JPG', upload_to=tour.models.Hotel_photo.get_hotel_upload_path, verbose_name='Фото'),
        ),
    ]
