# Generated by Django 5.1.2 on 2024-10-28 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_excursion_options_alter_tour_excursion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_description',
            field=models.TextField(default='Отель', verbose_name='Описание отелей'),
        ),
        migrations.AddField(
            model_name='tour_excursion',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 28)),
        ),
    ]
