# Generated by Django 5.1.2 on 2025-02-10 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_contact_message_alter_tour_excursion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата экскурсии'),
        ),
        migrations.AddField(
            model_name='contact',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место отправления'),
        ),
        migrations.AlterField(
            model_name='tour_excursion',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 10)),
        ),
    ]
