# Generated by Django 5.1.2 on 2025-02-16 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_contact_date_contact_place_alter_tour_excursion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour_excursion',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 16)),
        ),
    ]
